# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compiling the application
      run: mvn compile
    - name: Run the Unit Tests of the application
      run: mvn test
    - name: Package the compiled classes
      run: mvn -B package --file pom.xml
    - name: Run the Integration Tests
      run: mvn verify
    - name: Installing the application in the target folder
      run: mvn install
